### ISSUE TITLE
Page not found. 404

### ISSUE THREAD

**Issue by datomnurdin** [hasanavi/OpenCV-Unity3D-Object-Tracking#1]
This page not found, http://docs.opencv.org/trunk/doc/py_tutorials/py_setup/py_table_of_contents_setup/py_table_of_contents_setup.html#py-table-of-content-setup.

**Comment by hasanavi** [comment]
Thanks for pointing that out. They've updated the link. Here is the new one. http://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_setup/py_setup_in_windows/py_setup_in_windows.html

I'll update the readme file as well. 

Cheers.
