### ISSUE TITLE
ImportError: no module named video

### ISSUE THREAD

**Issue by andreierdoss** [hasanavi/OpenCV-Unity3D-Object-Tracking#2]
Hello,

Thank you for this library. I am trying it out on Mac OS X and after changing the line at the top of OpenCV/gameDemo.py for OpenCV to '/usr/local/Cellar/opencv/2.4.12/' I am getting the following error message when I try to run 'python OpenCV/gameDemo.py':

```
Traceback (most recent call last):
  File "OpenCV/gameDemo.py", line 7, in <module>
    import video
ImportError: No module named video
```

Please let me know what can be done to fix this. Thank you

**Comment by hasanavi** [comment]
Hi,

Could you please check video.py is available inside the opencv you are using?

Its usually seats under opencv/samples/python2/video.py

Thank you.
