### ISSUE TITLE
Hi, I got an error -- using python 3 ..

### ISSUE THREAD

**Issue by Guidosalimbeni** [hasanavi/OpenCV-Unity3D-Object-Tracking#6]
File "C:/Users/Proprietario/Downloads/OpenCV-Unity3D-Object-Tracking-master/OpenCV/gameDemo.py", line 94, in run
    sock.sendto(str(xPos) , (UDP_IP, UDP_PORT))

TypeError: a bytes-like object is required, not 'str'

**Comment by Guidosalimbeni** [comment]
ok.. line 94 changed to 
`sock.sendto(str(xPos).encode() , (UDP_IP, UDP_PORT))`

**Comment by hasanavi** [comment]
Thanks @Guidosalimbeni ,

It was written for Python 2.7 - thanks for raising the issue - i'll fix that :)

**Comment by abhilash1910** [comment]
I have added a PR regarding the changes for python 3.7 in comments. 
For rectifying:
b1=bytes(str(xPos),encode='utf-8')
sock.sendto(b1,(UDP_IP,UDP_PORT))

**Comment by hasanavi** [comment]
Appreciate it mate. Merged your PR :)

**Comment by abhilash1910** [comment]
Hi Hasan,
No worries.Great repository.
Thanks
Abhilash
